import { 
    Loader2, 
    FileText, 
    Calendar, 
    CheckCircle, 
    Search, 
    Mic,
    Upload,
    AlertCircle,
    Trash2,
    RefreshCw,
    Clock,
    ArrowLeft,
    Download,
    Copy,
    Book,
    User,
    Mail
} from 'lucide-react'

export const Icons = {
    spinner: Loader2,
    fileText: FileText,
    calendar: Calendar,
    checkCircle: CheckCircle,
    search: Search,
    mic: Mic,
    upload: Upload,
    alertCircle: AlertCircle,
    trash: Trash2,
    refresh: RefreshCw,
    clock: Clock,
    arrowLeft: ArrowLeft,
    download: Download,
    copy: Copy,
    book: Book,
    user: User,
    mail: Mail,
}
