import { 
    Loader2, 
    FileText, 
    Calendar, 
    CheckCircle, 
    Search, 
    Mic,
    Upload,
    AlertCircle,
    Trash2,
    RefreshCw,
    Clock,
    ArrowLeft,
    Download,
    Copy,
    Book,
    User,
    Mail,
    Building2,
    Home,
    Zap,
    PanelLeftClose,
    PanelLeftOpen,
    ChevronDown,
    ChevronRight,
    LogOut,
    Settings,
    Bell,
    Menu,
    X,
    Plus,
    Target,
    TrendingUp,
    Users,
    Briefcase,
    BarChart3,
    MessageSquare,
    ArrowRight,
    Sparkles,
    Shield,
    Globe,
    Play,
    Check,
    Eye,
    Edit,
} from 'lucide-react'

export const Icons = {
    spinner: Loader2,
    fileText: FileText,
    calendar: Calendar,
    checkCircle: CheckCircle,
    search: Search,
    mic: Mic,
    upload: Upload,
    alertCircle: AlertCircle,
    trash: Trash2,
    refresh: RefreshCw,
    clock: Clock,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    download: Download,
    copy: Copy,
    book: Book,
    user: User,
    mail: Mail,
    building: Building2,
    home: Home,
    zap: Zap,
    panelLeftClose: PanelLeftClose,
    panelLeftOpen: PanelLeftOpen,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    logOut: LogOut,
    settings: Settings,
    bell: Bell,
    menu: Menu,
    x: X,
    plus: Plus,
    target: Target,
    trendingUp: TrendingUp,
    users: Users,
    briefcase: Briefcase,
    barChart: BarChart3,
    message: MessageSquare,
    sparkles: Sparkles,
    shield: Shield,
    globe: Globe,
    play: Play,
    check: Check,
    eye: Eye,
    edit: Edit,
}
